apps/front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('',views.index,name='index'),
    path('search/',views.search,name='search'),
    path('usearch/',views.upper_search,name='usearch'),
    path('list/',views.document_list,name='list'),
    path('show/', views.ShowView.as_view(), name='show'),
    path('author_bar/', views.AuthorChartView.as_view(), name='author_bar'),
    path('line/', views.YearChartView.as_view(), name='line'),
    path('orginize_bar/', views.OrginiseChartView.as_view(), name='orginize_bar'),
    path('xpie/', views.XuekeChartView.as_view(), name='xpie'),
    path('qbar/', views.QikanChartView.as_view(), name='qbar'),
    path('catpie/', views.CatChartView.as_view(), name='cat_pie'),
    path('word/', views.WordChartView.as_view(), name='word'),
    path('relation/', views.RelationChartView.as_view(), name='relation'),
    path('test/', views.test, name='test'),

]

apps/users/urls.py
from django.urls import path
from .views import my_login,regist,my_logout,UserinfoView,ModifyPwdView,UploadImageView

app_name = 'auth'

urlpatterns = [
    path('login/',my_login,name='login'),
    path('regist/',regist,name='regist'),
    path('logout/',my_logout,name='logout'),
    path("info/", UserinfoView.as_view(), name='info'),
    path("resetpwd/", ModifyPwdView.as_view(), name='resetpwd'),
    # 用户图像上传
    path("image/upload/", UploadImageView.as_view(), name='image_upload'),
]

zhiwangShow/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/",include('apps.users.urls')),
    path("",include('apps.front.urls')),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]

apps/front/models.py
from django.db import models

# Create your models here.

class Document(models.Model):
    title = models.CharField(max_length=200,default="")
    author = models.CharField(max_length=200,default="")
    author_location = models.TextField(default="")
    acticle_source = models.CharField(max_length=200,default="")
    page_nums = models.CharField(max_length=50,default="")
    summary = models.TextField(default="")

    key_words = models.TextField(max_length=200,default="")
    add_time = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = "文献管理"
        verbose_name_plural = verbose_name


    def __str__(self):
        return self.title

apps/front/views.py
import re

from django.shortcuts import render
from apps.front.models import Document
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from pure_pagination import PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.db.models import Q, F
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from apps.utils.pyecharts_restful import JsonResponse
import db_tools.data.show_data as s_data

import json
from rest_framework.views import APIView
from pyecharts.charts import Bar, Line, Pie, WordCloud, Graph
from pyecharts import options as opts
from pyecharts.commons.utils import JsCode
from collections import Counter
from apps.utils import handle_memcache


# Create your views here.

def index(request):
    return render(request, 'front/index.html')


def search(request):
    search_cat_id = request.GET.get('searchtype') # 获取前端查询类型参数
    words = request.GET.get('words') # 获取前端查询关键词参数
    page = request.GET.get('page', 1)  # 获取页数

    # 根据查询条件和关键词内容，在数据库查找相关的内容
    if search_cat_id == 'title':
        if words:
            documents = Document.objects.filter(title__contains=words).all()
        else:
            documents = Document.objects.all()
    elif search_cat_id == 'author':
        if words:
            documents = Document.objects.filter(author__contains=words).all()
        else:
            documents = Document.objects.all()
    elif search_cat_id == 'source':
        if words:
            documents = Document.objects.filter(acticle_source__contains=words).all()
        else:
            documents = Document.objects.all()
    elif search_cat_id == 'keywords':
        if words:
            documents = Document.objects.filter(key_words__contains=words).all()
        else:
            documents = Document.objects.all()
    elif search_cat_id == 'summary':
        if words:
            documents = Document.objects.filter(summary__contains=words).all()
        else:
            documents = Document.objects.all()
    else:
        documents = Document.objects.all()

    # 搜索结果可视化核心代码
    author_list = []
    source_list = []
    year_list = []
    orginize_list = []
    key_words = []
    for document in documents:
        author_list += hander_author(document.author)
        source_list.append(document.acticle_source.split(",")[0])
        year_list.append(get_year(document.acticle_source.split(",")[1]))
        orginize_list.append(document.author_location.split(",")[0])
        key_words += handle_words(document.key_words)
    orginize_dict = Counter(orginize_list)
    author_dict = Counter(reversed(author_list))
    source_dict = Counter(source_list)
    year_dict = Counter(reversed(year_list))
    words_dict = Counter(key_words)

    words_list = sorted(words_dict.items(),key=lambda item:item[1])
    print(words_list)

    new_year = sorted(year_dict.items(),key=lambda item: item[0])
    new_year_name = []
    new_year_nums = []
    for item in new_year:
        new_year_name.append(item[0])
        new_year_nums.append(item[1])
    # memcache 存储词云数据
    handle_memcache.set_key("words",words_list)

    # memcached 存储作者信息
    handle_memcache.set_key("author_name",list(author_dict.keys())[:20])
    handle_memcache.set_key("author_nums",list(author_dict.values())[:20])

    # memcached 存储期刊信息
    handle_memcache.set_key("qikan_name",list(source_dict.keys())[:20])
    handle_memcache.set_key("qikan_nums",list(source_dict.values())[:20])

    # memcached 存储年份信息
    handle_memcache.set_key("year_name",new_year_name)
    handle_memcache.set_key("year_nums",new_year_nums)

    # memcached 存储机构信息
    handle_memcache.set_key("org_name",list(orginize_dict.keys()))
    handle_memcache.set_key("org_nums",list(orginize_dict.values()))

    p = Paginator(documents, 10, request=request)
    s_documents = p.page(page)
    # 查询内容返回前端模板，前端可以通过{{ documents }} 的方式获取数据
    context = {
        'documents': s_documents,
    }
    # 返回模板文件与数据
    return render(request, 'front/search.html', context=context)


def get_year(value):
    if re.search("\d+",value):
        return re.search("\d+",value).group()
    return ""

def handle_words(value):
    return value.split(",")

def hander_author(value):
    return [i.strip() for i in value.split(",")]

def document_list(request):
    all_documents = Document.objects.all()
    page = request.GET.get('page', 1)

    p = Paginator(all_documents, 20, request=request)
    documents = p.page(page)
    context = {
        'documents': documents,

    }
    return render(request, 'front/list.html', context=context)


#  可视化图表作者柱状图参数配置
def author_bar() -> Bar:
    x = handle_memcache.get_value("author_name")
    y = handle_memcache.get_value("author_nums")
    c = (
        Bar()
            .add_xaxis(x)
            .add_yaxis("作者", y)
            .set_global_opts(
            title_opts=opts.TitleOpts(title="作者数量", subtitle="相关文章数量"), # 设置标题
            xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=45)), # 横轴设置字体倾斜45°，可显示全部作者名称
        )
            .dump_options_with_quotes() # 返回Json 格式的数据，前端解析调用
    )
    return c


def orginize_bar() -> Bar:
    o_x = handle_memcache.get_value("org_name")
    o_y = handle_memcache.get_value("org_nums")
    c = (
        Bar()
            .add_xaxis(o_x)
            .add_yaxis("机构", o_y, category_gap="60%")
            .set_series_opts(
            itemstyle_opts={
                "normal": {
                    "color": JsCode(
                        """new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                    offset: 0,
                    color: 'rgba(0, 122, 255, 1)'
                }, {
                    offset: 1,
                    color: 'rgba(0, 77, 167, 1)'
                }], false)"""
                    ),
                    "barBorderRadius": [30, 30, 30, 30],
                    "shadowColor": "rgb(0, 160, 221)",
                }
            }
        )
            .set_global_opts(
            title_opts=opts.TitleOpts(title="机构"),
            xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=45)),
        )
            .dump_options_with_quotes()
    )
    return c


def year_line():
    x = handle_memcache.get_value("year_name")
    y = handle_memcache.get_value("year_nums")


    line2 = (
        Line()
            .set_global_opts(
            tooltip_opts=opts.TooltipOpts(is_show=False),
            xaxis_opts=opts.AxisOpts(type_="category"),
            yaxis_opts=opts.AxisOpts(
                type_="value",
                axistick_opts=opts.AxisTickOpts(is_show=True),
                splitline_opts=opts.SplitLineOpts(is_show=True),
            ),
        )
            .add_xaxis(xaxis_data=x)
            .add_yaxis(
            series_name="",
            y_axis=y,
            symbol="emptyCircle",
            is_symbol_show=True,
            label_opts=opts.LabelOpts(is_show=False),
        )
            # 设置 boundary_gap 的时候一定要放在最后一个配置项里, 不然会被覆盖
            .dump_options_with_quotes()
    )
    return line2


def xueke_pie():
    data1 = handle_memcache.get_value("qikan_name")
    data2 = handle_memcache.get_value("qikan_nums")
    c = (
        Pie()
            .add(
            "",
            [
                list(z)
                for z in zip(
                data1,
                data2,
            )
            ],
            center=["40%", "50%"],
        )
            .set_global_opts(
            title_opts=opts.TitleOpts(title="期刊占比"),
            legend_opts=opts.LegendOpts(type_="scroll", pos_left="80%", orient="vertical"),
        )
            .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
            .dump_options_with_quotes()
    )
    return c


def qikan_bar() -> Bar:
    x = handle_memcache.get_value("qikan_name")
    y = handle_memcache.get_value("qikan_nums")
    c = (
        Bar()
            .add_xaxis(x)
            .add_yaxis("期刊", y)
            .reversal_axis()
            .set_series_opts(label_opts=opts.LabelOpts(position="right"))
            .set_global_opts(title_opts=opts.TitleOpts(title="期刊数量展示"))
            .dump_options_with_quotes()
    )
    return c


def cat_pie():
    data1 = s_data.cat
    data2 = s_data.cat_nums
    c = (
        Pie()
            .add(
            "",
            [list(z) for z in zip(data1, data2)],
            radius=["40%", "55%"],
            label_opts=opts.LabelOpts(
                position="outside",
                formatter="{a|{a}}{abg|}\n{hr|}\n {b|{b}: }{c}  {per|{d}%}  ",
                background_color="#eee",
                border_color="#aaa",
                border_width=1,
                border_radius=4,
                rich={
                    "a": {"color": "#999", "lineHeight": 22, "align": "center"},
                    "abg": {
                        "backgroundColor": "#e3e3e3",
                        "width": "100%",
                        "align": "right",
                        "height": 22,
                        "borderRadius": [4, 4, 0, 0],
                    },
                    "hr": {
                        "borderColor": "#aaa",
                        "width": "100%",
                        "borderWidth": 0.5,
                        "height": 0,
                    },
                    "b": {"fontSize": 16, "lineHeight": 33},
                    "per": {
                        "color": "#eee",
                        "backgroundColor": "#334455",
                        "padding": [2, 4],
                        "borderRadius": 2,
                    },
                },
            ),
        )
            .set_global_opts(title_opts=opts.TitleOpts(title="资源类型展示"))
            .dump_options_with_quotes()
    )
    return c


def wordshow():
    words_list = handle_memcache.get_value('words')[::-1][1:50]
    c = (
        WordCloud()
            .add(series_name="热点分析", data_pair=words_list, word_size_range=[6, 66],shape="star")

templates/front/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页-论文文献检索可视化系统</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'js/sweetalert/sweetalert.css' %}" crossorigin="anonymous">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/dxajax.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xtalert.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="padding:0 20px" href="/">
                <img src="{% static 'img/logo4.png' %}" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li style="text-align: center"><a href="/">论文文献查询系统</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'front:list' %}">文献列表</a></li>
                <li class="dropdown">
                    {% if request.user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                    {% else %}
                        <li><a href="{% url 'auth:login' %}">请登录</a></li>
                    {% endif %}
                <ul class="dropdown-menu">
                    <li><a href="{% url 'auth:info' %}">个人资料</a></li>
                    {% if request.user.is_staff %}
                        <li><a href="/admin/login/">系统管理</a></li>
                    {% endif %}
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'auth:logout' %}">注销登录</a></li>
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
    <div class="title">
        <h2>文献检索系统</h2>
    </div>
    <div class="search-box" id="simple-box">
        <div class="row">
            <form action="/search/" method="get">
                <div class="col-lg-2">
                    <select name="searchtype" id="search-cat-id">
                        <option value="title">主题</option>
                        <option value="author">作者</option>
                        <option value="source">出处</option>
                        <option value="keywords">关键词</option>
                        <option value="summary">摘要</option>
                    </select>
                </div>
                <div class="col-lg-8">
                    <input name="words" type="text" class="form-control" aria-label="">
                </div><!-- /.col-lg-6 -->
                <div class="col-lg-1">
                    <input type="submit" class="btn btn-primary" value="搜索">
                </div>
                <div class="col-lg-1">
                    <span class="upper-btn btn btn-primary upper" id="upper-show">高级搜索</span>
                </div>
            </form>
        </div><!-- /.row -->
    </div>
    <div class="upper-box" style="display: none;margin-top: 30px">
        <form action="/usearch/" method="get">
            <div class="search-box" style="margin-bottom: 10px">
                <div class="row">
                        <div class="col-md-2">
                            <select name="searchtype1" id="search-cat-id1">
                                <option value="title">主题</option>
                                <option value="author">作者</option>
                                <option value="keywords">关键词</option>
                                <option value="summary">摘要</option>
                            </select>
                        </div>
                        <div class="col-md-8">
                            <input name="upper_words1" type="text" class="form-control" aria-label="">
                        </div><!-- /.col-lg-6 -->
                        <div class="col-md-2">
                            <select name="searchtype_logic" id="search-cat-id-logic">
                                <option value="and">与</option>
                                <option value="or">或</option>
                            </select>
                        </div>
                </div><!-- /.row -->
            </div>
            <div class="search-box" style="margin-top: 10px;">
                <div class="row">
                        <div class="col-md-2">
                            <select name="searchtype2" id="search-cat-id2">
                                <option value="title">主题</option>
                                <option value="author">作者</option>
                                <option value="keywords">关键词</option>
                                <option value="summary">摘要</option>
                            </select>
                        </div>
                        <div class="col-md-8">
                            <input name="upper_words2" type="text" class="form-control" aria-label="">
                        </div><!-- /.col-lg-6 -->
                        <div class="col-md-1">
                            <span type="submit" class="btn btn-primary" id="back">返回</span>
                        </div>
                </div><!-- /.row -->
            </div>
            <div class="search2">
                <input type="submit" class="btn btn-success" value="搜索">
            </div>
        </form>
    </div>

</div>
<div class="tips">
    <ul>
        <li>关于我们</li>
        <li>版权公告</li>
        <li>在线咨询</li>
        <li>用户建议</li>
    </ul>
</div>
</body>
</html>

templates/front/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表-论文文献检索可视化系统</title>
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'js/sweetalert/sweetalert.css' %}" crossorigin="anonymous">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/dxajax.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xtalert.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body style="background-color: #d0e9c6">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="padding:0 20px" href="/">
                <img src="{% static 'img/logo4.png' %}" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li style="text-align: center"><a href="/">论文文献查询系统</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">搜索</a></li>
                <li><a href="#">文献列表</a></li>
                <li class="dropdown">
                    {% if request.user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                    {% else %}
                        <li><a href="{% url 'auth:login' %}">请登录</a></li>
                    {% endif %}
                <ul class="dropdown-menu">
                    <li><a href="{% url 'auth:info' %}">个人资料</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'auth:logout' %}">注销登录</a></li>
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
    <div class="search-box">
        <div class="item-group">
            {% for document in documents.object_list %}
                <div class="item">
                    <div class="article-title">
                        <h3>{{ document.title }}</h3>
                    </div>
                    <div class="info">
                        <span>作者：{{ document.author }}</span>
                        <span>出处：{{ document.acticle_source }}</span>
                    </div>
                    <div class="summary">
                        <p>{{ document.summary |truncatechars:200 }}</p>
                    </div>
                    <div class="bottom-box">
                        {% if document.key_words != 'nan' %}
                            <span>关键词：{{ document.key_words }}</span>
                        {% else %}
                            <span>关键词：  </span>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    <div class="pagebox">
        <ul class="pagegroup">
            {#                                分页判断#}
            {% if documents.has_previous %}
                <li class="long"><a href="?page={{ documents.previous_page_number }}"><<</a></li>
            {% endif %}
            {% for page in documents.pages %}
                {% if page %}
                    {% ifequal page courses.number %}
                        {#                                            page.number是当前的页数#}
                        {#                                            page.querystring  是字符串page=page.number#}
                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li class=""><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                {% endif %}
            {% endfor %}
            {% if documents.has_next %}
                <li class="long"><a href="?page={{ documents.next_page_number }}">>></a></li>
            {% endif %}
        </ul>
    </div>
    <div class="tips">
        <ul>
            <li>关于我们</li>
            <li>版权公告</li>
            <li>在线咨询</li>
            <li>用户建议</li>
        </ul>
    </div>
</div>
</body>
</html>

templates/front/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索-论文文献检索可视化系统</title>
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'js/sweetalert/sweetalert.css' %}" crossorigin="anonymous">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/dxajax.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xtalert.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body style="background-color: #d0e9c6">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="padding:0 20px" href="/">
                <img src="{% static 'img/logo4.png' %}" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li style="text-align: center"><a href="/">论文文献查询系统</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">搜索</a></li>
                <li><a href="{% url 'front:show' %}">可视化</a></li>
                <li><a href="#">文献列表</a></li>
                <li class="dropdown">
                    {% if request.user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                    {% else %}
                        <li><a href="{% url 'auth:login' %}">请登录</a></li>
                    {% endif %}
                <ul class="dropdown-menu">
                    <li><a href="{% url 'auth:info' %}">个人资料</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'auth:logout' %}">注销登录</a></li>
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
    {% if documents %}
        <div class="search-box">
            <div class="item-group">
                {% for document in documents.object_list %}
                    <div class="item">
                        <div class="article-title">
                            <h3>{{ document.title }}</h3>
                        </div>
                        <div class="info">
                            <span>作者：{{ document.author }}</span>
                            <span>出处：{{ document.acticle_source }}</span>
                        </div>
                        <div class="summary">
                            <p>{{ document.summary |truncatechars:200 }}</p>
                        </div>
                        <div class="bottom-box">
                            {% if document.key_words != 'nan' %}
                                <span>关键词：{{ document.key_words }}</span>
                            {% else %}
                                <span>关键词：  </span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
        {% else %}
        <div class="no-result">
        <h3>未查询到相关数据，请重新输入检索条件！</h3>
        </div>
    {% endif %}
    <div class="pagebox">
        <ul class="pagegroup">
            {#                                分页判断#}
            {% if documents.has_previous %}
                <li class="long"><a href="?page={{ documents.previous_page_number }}"><<</a></li>
            {% endif %}
            {% for page in documents.pages %}
                {% if page %}
                    {% ifequal page courses.number %}
                        {#                                            page.number是当前的页数#}
                        {#                                            page.querystring  是字符串page=page.number#}
                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li class=""><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                {% endif %}
            {% endfor %}
            {% if documents.has_next %}
                <li class="long"><a href="?page={{ documents.next_page_number }}">>></a></li>
            {% endif %}
        </ul>
    </div>

</div>
<div class="tips">
    <ul>
        <li>关于我们</li>
        <li>版权公告</li>
        <li>在线咨询</li>
        <li>用户建议</li>
    </ul>
</div>
</body>
</html>

templates/front/simple_chart.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="../../../static/js/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <title>{{ chart.page_title }}</title>
    {{ macro.render_chart_dependencies(chart) }}
</head>
<body>
<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">折线图</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">柱状图</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">直方图</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">词云图</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
        {{ macro.render_chart_content(chart)}}
    </div>
    <div role="tabpanel" class="tab-pane" id="profile"></div>
    <div role="tabpanel" class="tab-pane" id="messages">...</div>
    <div role="tabpanel" class="tab-pane" id="settings">...</div>
  </div>

</div>

</body>
</html>